### ISSUE TITLE
Testing on Windows 11

### ISSUE THREAD

**Issue by masfoobar** [laytan/odin-http#12]
Grabbed odin-http earlier today.

Copied the 'Server Example' as presented on Readme.md

When I run I receive these results and terminates...

```
[DEBUG] --- [2023-09-01 14:18:48] [server.odin:108:listen_and_serve()] accepting connections
[DEBUG] --- [2023-09-01 14:18:48] [server.odin:113:listen_and_serve()] starting event loop
c:/Users/user1/projects/httpplay/odin-http/nbio/nbio_windows.odin(107:4) runtime assertion
```

I did comment this line (107 in nbio_windows.odin) in a hope it might spit out some additionals errors to help detect the problem. However, when I reran the results are the same, except the last line.

Am I missing anything or doing something incorrectly?
Happy to help with queries with my setup.

Thanks.

**Comment by laytan** [comment]
Hello! This was fixed in a recent commit into Odin itself (https://github.com/odin-lang/Odin/pull/2775) can you try updating, I am pretty sure that is what is going on here.

**Comment by masfoobar** [comment]
Will try again tomorrow -- and update you. Thank you!
