### ISSUE TITLE
Cannot build with "-debug"

### ISSUE THREAD

**Issue by Dreamshade-1911** [laytan/odin-http#36]
_I'm not sure if I should open this issue here or on the Odin repository, if it's the latter you can close this and I'll post it on there instead._

Building the server example from the readme with the `-debug` flag makes the compiler silently fail with a 127 error code.

```sh
> make
odin build src -out:bin/test.exe -collection:third_party=third_party -show-timings -o:none -debug
make: *** [makefile:21: build] Error 127
```

I tested all flag combinations, and `-debug` is the sole culprit.

**Comment by laytan** [comment]
Is this every single time you try it, and only with this project? This happens to me too but not on every single build, and I would also get some error message.

I also tried compiling the readme example a couple of times just now and it worked every time.

In any case this would be either an Odin issue or something with your environment because you either need to get an error message or the compilation should work.

**Comment by Dreamshade-1911** [comment]
I see, yeah it's every time, other projects compile just fine with the debug flag. I'll open an issue on the Odin repo, then.

**Comment by laytan** [comment]
Hey, I just double-checked on all my machines (windows 11, m1 mac, pop_os!) and the example compiles fine for me, with and without -debug

**Comment by Dreamshade-1911** [comment]
Just pulled the repository and was able to compile with debug. Just to check that I wasn't going mad I reverted to the old commit to try it and it failed.

```sh
test\third_party\odin-http> git checkout aacea28e5678a473f4836c4ff08288129f695afc
Note: switching to 'aacea28e5678a473f4836c4ff08288129f695afc'.

test\third_party\odin-http> cd ../..   

test>make
odin build src -out:bin/test.exe -collection:third_party=third_party -show-timings -max-error-count:4 -o:none -debug
make: *** [makefile:21: build] Error 127

test>cd third_party/odin-http

test\third_party\odin-http> git checkout main
Previous HEAD position was aacea28 cont. #34 also remove assertion above the loop
Switched to branch 'main'
Your branch is up to date with 'origin/main'.

test\third_party\odin-http> cd ../..

test>make
odin build src -out:bin/test.exe -collection:third_party=third_party -show-timings -max-error-count:4 -o:none -debug
Total Time        -   811.183 ms - 100.00%
initialization    -     6.215 ms -   0.76%
parse files       -     9.633 ms -   1.18%
type check        -    40.425 ms -   4.98%
LLVM API Code Gen -   673.888 ms -  83.07%
msvc-link         -    81.018 ms -   9.98%
Build finished successfully.
```

**Comment by laytan** [comment]
LOL glad it works now!
