### ISSUE TITLE
Client get example does not work - assertion error

### ISSUE THREAD

**Issue by FreerGit** [laytan/odin-http#37]
the proc `headers_set_unsafe` panics on the given get request example in the README

the `readonly` tag is not set in `Headers` struct and therefor panics on the call from line 478 in client.odin.

I may have understood something wrong but I just copy pasted the code.

```
main :: proc() {
	res, err := client.get("https://www.google.com/")
	if err != nil {
		fmt.printf("Request failed: %s", err)
		return
	}
	defer client.response_destroy(&res)

	fmt.printf("Status: %s\n", res.status)
	fmt.printf("Headers: %v\n", res.headers)
	fmt.printf("Cookies: %v\n", res.cookies)
	body, allocation, berr := client.response_body(&res)
	if berr != nil {
		fmt.printf("Error retrieving response body: %s", berr)
		return
	}
	defer client.body_destroy(body, allocation)

	fmt.println(body)
}
```

And got:
Status: OK
Headers: .....
Cookies: ....
..../http/headers.odin(48:2) runtime assertion

**Comment by laytan** [comment]
Hey! Thanks for filing an issue, I quickly pushed that change the other day and a trivial test worked but this one slipped. it is now fixed.
